package com.a612.springmvc.entity;

public class Goodsitem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsitem.goodsitem_id
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    private Integer goodsitemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsitem.goods_id
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsitem.goods_num
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    private Integer goodsNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsitem.goods_prize
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    private Float goodsPrize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsitem.goodsitem_prize
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    private Float goodsitemPrize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsitem.order_id
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    private Integer orderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsitem
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    public Goodsitem(Integer goodsitemId, Integer goodsId, Integer goodsNum, Float goodsPrize, Float goodsitemPrize, Integer orderId) {
        this.goodsitemId = goodsitemId;
        this.goodsId = goodsId;
        this.goodsNum = goodsNum;
        this.goodsPrize = goodsPrize;
        this.goodsitemPrize = goodsitemPrize;
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsitem
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    public Goodsitem() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsitem.goodsitem_id
     *
     * @return the value of goodsitem.goodsitem_id
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    public Integer getGoodsitemId() {
        return goodsitemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsitem.goodsitem_id
     *
     * @param goodsitemId the value for goodsitem.goodsitem_id
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    public void setGoodsitemId(Integer goodsitemId) {
        this.goodsitemId = goodsitemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsitem.goods_id
     *
     * @return the value of goodsitem.goods_id
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsitem.goods_id
     *
     * @param goodsId the value for goodsitem.goods_id
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsitem.goods_num
     *
     * @return the value of goodsitem.goods_num
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    public Integer getGoodsNum() {
        return goodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsitem.goods_num
     *
     * @param goodsNum the value for goodsitem.goods_num
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    public void setGoodsNum(Integer goodsNum) {
        this.goodsNum = goodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsitem.goods_prize
     *
     * @return the value of goodsitem.goods_prize
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    public Float getGoodsPrize() {
        return goodsPrize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsitem.goods_prize
     *
     * @param goodsPrize the value for goodsitem.goods_prize
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    public void setGoodsPrize(Float goodsPrize) {
        this.goodsPrize = goodsPrize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsitem.goodsitem_prize
     *
     * @return the value of goodsitem.goodsitem_prize
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    public Float getGoodsitemPrize() {
        return goodsitemPrize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsitem.goodsitem_prize
     *
     * @param goodsitemPrize the value for goodsitem.goodsitem_prize
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    public void setGoodsitemPrize(Float goodsitemPrize) {
        this.goodsitemPrize = goodsitemPrize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsitem.order_id
     *
     * @return the value of goodsitem.order_id
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsitem.order_id
     *
     * @param orderId the value for goodsitem.order_id
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
}