package com.a612.springmvc.entity;

public class Goodstype {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodstype.goodstype_id
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    private Integer goodstypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodstype.goodstype_name
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    private String goodstypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodstype.goodstype_description
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    private String goodstypeDescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodstype
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    public Goodstype(Integer goodstypeId, String goodstypeName, String goodstypeDescription) {
        this.goodstypeId = goodstypeId;
        this.goodstypeName = goodstypeName;
        this.goodstypeDescription = goodstypeDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodstype
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    public Goodstype() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodstype.goodstype_id
     *
     * @return the value of goodstype.goodstype_id
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    public Integer getGoodstypeId() {
        return goodstypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodstype.goodstype_id
     *
     * @param goodstypeId the value for goodstype.goodstype_id
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    public void setGoodstypeId(Integer goodstypeId) {
        this.goodstypeId = goodstypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodstype.goodstype_name
     *
     * @return the value of goodstype.goodstype_name
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    public String getGoodstypeName() {
        return goodstypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodstype.goodstype_name
     *
     * @param goodstypeName the value for goodstype.goodstype_name
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    public void setGoodstypeName(String goodstypeName) {
        this.goodstypeName = goodstypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodstype.goodstype_description
     *
     * @return the value of goodstype.goodstype_description
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    public String getGoodstypeDescription() {
        return goodstypeDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodstype.goodstype_description
     *
     * @param goodstypeDescription the value for goodstype.goodstype_description
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    public void setGoodstypeDescription(String goodstypeDescription) {
        this.goodstypeDescription = goodstypeDescription;
    }
}