package com.a612.springmvc.entity;

public class Goodsinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsinfo.goodsId
     *
     * @mbggenerated Thu May 02 17:20:43 CST 2019
     */
    private Integer goodsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsinfo.goodsTypeid
     *
     * @mbggenerated Thu May 02 17:20:43 CST 2019
     */
    private Integer goodstypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsinfo.goodsName
     *
     * @mbggenerated Thu May 02 17:20:43 CST 2019
     */
    private String goodsname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsinfo.goodsMoney
     *
     * @mbggenerated Thu May 02 17:20:43 CST 2019
     */
    private Float goodsmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsinfo.goodsNote
     *
     * @mbggenerated Thu May 02 17:20:43 CST 2019
     */
    private String goodsnote;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsinfo
     *
     * @mbggenerated Thu May 02 17:20:43 CST 2019
     */
    public Goodsinfo(Integer goodsid, Integer goodstypeid, String goodsname, Float goodsmoney, String goodsnote) {
        this.goodsid = goodsid;
        this.goodstypeid = goodstypeid;
        this.goodsname = goodsname;
        this.goodsmoney = goodsmoney;
        this.goodsnote = goodsnote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsinfo
     *
     * @mbggenerated Thu May 02 17:20:43 CST 2019
     */
    public Goodsinfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsinfo.goodsId
     *
     * @return the value of goodsinfo.goodsId
     *
     * @mbggenerated Thu May 02 17:20:43 CST 2019
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsinfo.goodsId
     *
     * @param goodsid the value for goodsinfo.goodsId
     *
     * @mbggenerated Thu May 02 17:20:43 CST 2019
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsinfo.goodsTypeid
     *
     * @return the value of goodsinfo.goodsTypeid
     *
     * @mbggenerated Thu May 02 17:20:43 CST 2019
     */
    public Integer getGoodstypeid() {
        return goodstypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsinfo.goodsTypeid
     *
     * @param goodstypeid the value for goodsinfo.goodsTypeid
     *
     * @mbggenerated Thu May 02 17:20:43 CST 2019
     */
    public void setGoodstypeid(Integer goodstypeid) {
        this.goodstypeid = goodstypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsinfo.goodsName
     *
     * @return the value of goodsinfo.goodsName
     *
     * @mbggenerated Thu May 02 17:20:43 CST 2019
     */
    public String getGoodsname() {
        return goodsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsinfo.goodsName
     *
     * @param goodsname the value for goodsinfo.goodsName
     *
     * @mbggenerated Thu May 02 17:20:43 CST 2019
     */
    public void setGoodsname(String goodsname) {
        this.goodsname = goodsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsinfo.goodsMoney
     *
     * @return the value of goodsinfo.goodsMoney
     *
     * @mbggenerated Thu May 02 17:20:43 CST 2019
     */
    public Float getGoodsmoney() {
        return goodsmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsinfo.goodsMoney
     *
     * @param goodsmoney the value for goodsinfo.goodsMoney
     *
     * @mbggenerated Thu May 02 17:20:43 CST 2019
     */
    public void setGoodsmoney(Float goodsmoney) {
        this.goodsmoney = goodsmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsinfo.goodsNote
     *
     * @return the value of goodsinfo.goodsNote
     *
     * @mbggenerated Thu May 02 17:20:43 CST 2019
     */
    public String getGoodsnote() {
        return goodsnote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsinfo.goodsNote
     *
     * @param goodsnote the value for goodsinfo.goodsNote
     *
     * @mbggenerated Thu May 02 17:20:43 CST 2019
     */
    public void setGoodsnote(String goodsnote) {
        this.goodsnote = goodsnote;
    }
}