package com.a612.springmvc.entity;

public class Goodstype {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodstype.typeid
     *
     * @mbggenerated Thu May 02 17:20:43 CST 2019
     */
    private Integer typeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodstype.typename
     *
     * @mbggenerated Thu May 02 17:20:43 CST 2019
     */
    private String typename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodstype.typenote
     *
     * @mbggenerated Thu May 02 17:20:43 CST 2019
     */
    private String typenote;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodstype
     *
     * @mbggenerated Thu May 02 17:20:43 CST 2019
     */
    public Goodstype(Integer typeid, String typename, String typenote) {
        this.typeid = typeid;
        this.typename = typename;
        this.typenote = typenote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodstype
     *
     * @mbggenerated Thu May 02 17:20:43 CST 2019
     */
    public Goodstype() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodstype.typeid
     *
     * @return the value of goodstype.typeid
     *
     * @mbggenerated Thu May 02 17:20:43 CST 2019
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodstype.typeid
     *
     * @param typeid the value for goodstype.typeid
     *
     * @mbggenerated Thu May 02 17:20:43 CST 2019
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodstype.typename
     *
     * @return the value of goodstype.typename
     *
     * @mbggenerated Thu May 02 17:20:43 CST 2019
     */
    public String getTypename() {
        return typename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodstype.typename
     *
     * @param typename the value for goodstype.typename
     *
     * @mbggenerated Thu May 02 17:20:43 CST 2019
     */
    public void setTypename(String typename) {
        this.typename = typename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodstype.typenote
     *
     * @return the value of goodstype.typenote
     *
     * @mbggenerated Thu May 02 17:20:43 CST 2019
     */
    public String getTypenote() {
        return typenote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodstype.typenote
     *
     * @param typenote the value for goodstype.typenote
     *
     * @mbggenerated Thu May 02 17:20:43 CST 2019
     */
    public void setTypenote(String typenote) {
        this.typenote = typenote;
    }
}