package com.a612.springmvc.entity;

public class Goodsinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsinfo.goods_id
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsinfo.goodstype_id
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    private Integer goodstypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsinfo.goods_name
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsinfo.goods_prize
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    private Float goodsPrize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsinfo.goods_note
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    private String goodsNote;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsinfo
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    public Goodsinfo(Integer goodsId, Integer goodstypeId, String goodsName, Float goodsPrize, String goodsNote) {
        this.goodsId = goodsId;
        this.goodstypeId = goodstypeId;
        this.goodsName = goodsName;
        this.goodsPrize = goodsPrize;
        this.goodsNote = goodsNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsinfo
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    public Goodsinfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsinfo.goods_id
     *
     * @return the value of goodsinfo.goods_id
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsinfo.goods_id
     *
     * @param goodsId the value for goodsinfo.goods_id
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsinfo.goodstype_id
     *
     * @return the value of goodsinfo.goodstype_id
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    public Integer getGoodstypeId() {
        return goodstypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsinfo.goodstype_id
     *
     * @param goodstypeId the value for goodsinfo.goodstype_id
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    public void setGoodstypeId(Integer goodstypeId) {
        this.goodstypeId = goodstypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsinfo.goods_name
     *
     * @return the value of goodsinfo.goods_name
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsinfo.goods_name
     *
     * @param goodsName the value for goodsinfo.goods_name
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsinfo.goods_prize
     *
     * @return the value of goodsinfo.goods_prize
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    public Float getGoodsPrize() {
        return goodsPrize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsinfo.goods_prize
     *
     * @param goodsPrize the value for goodsinfo.goods_prize
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    public void setGoodsPrize(Float goodsPrize) {
        this.goodsPrize = goodsPrize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsinfo.goods_note
     *
     * @return the value of goodsinfo.goods_note
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    public String getGoodsNote() {
        return goodsNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsinfo.goods_note
     *
     * @param goodsNote the value for goodsinfo.goods_note
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    public void setGoodsNote(String goodsNote) {
        this.goodsNote = goodsNote;
    }
}