package com.a612.springmvc.dao;

import com.a612.springmvc.entity.Admin;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface AdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    @Delete({
        "delete from admin",
        "where admin_id = #{adminId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    @Insert({
        "insert into admin (admin_id, admin_name, ",
        "admin_pwd, admin_level)",
        "values (#{adminId,jdbcType=INTEGER}, #{adminName,jdbcType=VARCHAR}, ",
        "#{adminPwd,jdbcType=VARCHAR}, #{adminLevel,jdbcType=INTEGER})"
    })
    int insert(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    int insertSelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    @Select({
        "select",
        "admin_id, admin_name, admin_pwd, admin_level",
        "from admin",
        "where admin_id = #{adminId,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Admin selectByPrimaryKey(Integer adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    int updateByPrimaryKeySelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    @Update({
        "update admin",
        "set admin_name = #{adminName,jdbcType=VARCHAR},",
          "admin_pwd = #{adminPwd,jdbcType=VARCHAR},",
          "admin_level = #{adminLevel,jdbcType=INTEGER}",
        "where admin_id = #{adminId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Admin record);
}