package com.a612.springmvc.dao;

import com.a612.springmvc.entity.Goodsorder;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface GoodsorderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsorder
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    @Delete({
        "delete from goodsorder",
        "where order_id = #{orderId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsorder
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    @Insert({
        "insert into goodsorder (order_id, user_id, ",
        "order_date, order_price, ",
        "order_message, order_addressee, ",
        "order_address, order_phone, ",
        "order_status)",
        "values (#{orderId,jdbcType=INTEGER}, #{userId,jdbcType=INTEGER}, ",
        "#{orderDate,jdbcType=TIMESTAMP}, #{orderPrice,jdbcType=REAL}, ",
        "#{orderMessage,jdbcType=VARCHAR}, #{orderAddressee,jdbcType=VARCHAR}, ",
        "#{orderAddress,jdbcType=VARCHAR}, #{orderPhone,jdbcType=VARCHAR}, ",
        "#{orderStatus,jdbcType=VARCHAR})"
    })
    int insert(Goodsorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsorder
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    int insertSelective(Goodsorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsorder
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    @Select({
        "select",
        "order_id, user_id, order_date, order_price, order_message, order_addressee, ",
        "order_address, order_phone, order_status",
        "from goodsorder",
        "where order_id = #{orderId,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Goodsorder selectByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsorder
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    int updateByPrimaryKeySelective(Goodsorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsorder
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    @Update({
        "update goodsorder",
        "set user_id = #{userId,jdbcType=INTEGER},",
          "order_date = #{orderDate,jdbcType=TIMESTAMP},",
          "order_price = #{orderPrice,jdbcType=REAL},",
          "order_message = #{orderMessage,jdbcType=VARCHAR},",
          "order_addressee = #{orderAddressee,jdbcType=VARCHAR},",
          "order_address = #{orderAddress,jdbcType=VARCHAR},",
          "order_phone = #{orderPhone,jdbcType=VARCHAR},",
          "order_status = #{orderStatus,jdbcType=VARCHAR}",
        "where order_id = #{orderId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Goodsorder record);
}