package com.a612.springmvc.dao;

import com.a612.springmvc.entity.Goodstype;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface GoodstypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodstype
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    @Delete({
        "delete from goodstype",
        "where goodstype_id = #{goodstypeId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer goodstypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodstype
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    @Insert({
        "insert into goodstype (goodstype_id, goodstype_name, ",
        "goodstype_description)",
        "values (#{goodstypeId,jdbcType=INTEGER}, #{goodstypeName,jdbcType=VARCHAR}, ",
        "#{goodstypeDescription,jdbcType=LONGVARCHAR})"
    })
    int insert(Goodstype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodstype
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    int insertSelective(Goodstype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodstype
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    @Select({
        "select",
        "goodstype_id, goodstype_name, goodstype_description",
        "from goodstype",
        "where goodstype_id = #{goodstypeId,jdbcType=INTEGER}"
    })
    @ResultMap("ResultMapWithBLOBs")
    Goodstype selectByPrimaryKey(Integer goodstypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodstype
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    int updateByPrimaryKeySelective(Goodstype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodstype
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    @Update({
        "update goodstype",
        "set goodstype_name = #{goodstypeName,jdbcType=VARCHAR},",
          "goodstype_description = #{goodstypeDescription,jdbcType=LONGVARCHAR}",
        "where goodstype_id = #{goodstypeId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKeyWithBLOBs(Goodstype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodstype
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    @Update({
        "update goodstype",
        "set goodstype_name = #{goodstypeName,jdbcType=VARCHAR}",
        "where goodstype_id = #{goodstypeId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Goodstype record);
}