package com.a612.springmvc.dao;

import com.a612.springmvc.entity.Goodsitem;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface GoodsitemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsitem
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    @Delete({
        "delete from goodsitem",
        "where goodsitem_id = #{goodsitemId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer goodsitemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsitem
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    @Insert({
        "insert into goodsitem (goodsitem_id, goods_id, ",
        "goods_num, goods_prize, ",
        "goodsitem_prize, order_id)",
        "values (#{goodsitemId,jdbcType=INTEGER}, #{goodsId,jdbcType=INTEGER}, ",
        "#{goodsNum,jdbcType=INTEGER}, #{goodsPrize,jdbcType=REAL}, ",
        "#{goodsitemPrize,jdbcType=REAL}, #{orderId,jdbcType=INTEGER})"
    })
    int insert(Goodsitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsitem
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    int insertSelective(Goodsitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsitem
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    @Select({
        "select",
        "goodsitem_id, goods_id, goods_num, goods_prize, goodsitem_prize, order_id",
        "from goodsitem",
        "where goodsitem_id = #{goodsitemId,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Goodsitem selectByPrimaryKey(Integer goodsitemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsitem
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    int updateByPrimaryKeySelective(Goodsitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsitem
     *
     * @mbggenerated Mon May 06 00:20:56 CST 2019
     */
    @Update({
        "update goodsitem",
        "set goods_id = #{goodsId,jdbcType=INTEGER},",
          "goods_num = #{goodsNum,jdbcType=INTEGER},",
          "goods_prize = #{goodsPrize,jdbcType=REAL},",
          "goodsitem_prize = #{goodsitemPrize,jdbcType=REAL},",
          "order_id = #{orderId,jdbcType=INTEGER}",
        "where goodsitem_id = #{goodsitemId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Goodsitem record);
}